# experimenta.cc -> http://experimenta-landing:3000 over the proxy network
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name experimenta.cc;
    include /config/nginx/ssl.conf;
    include /config/nginx/no-crawl.conf;
    client_max_body_size 0;

    location = /robots.txt {
        include /config/nginx/no-crawl.conf;
        default_type text/plain;
        return 200 "User-agent: *
Disallow: /
";
    }

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        include /config/nginx/no-crawl.conf;
        set $upstream_app experimenta-landing;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
